#!/bin/zsh

# ------------------------------------------------
# GLOBALS ----------------------------------------
# ------------------------------------------------
_upload_port=$SUBNET_PREFIX"55"

_environment="uno"

# ------------------------------------------------
# MAIN -------------------------------------------
# ------------------------------------------------

# Determine upload port
# ------------------------------------------------
_upload_port=`ls /dev/tty.* | grep -o "usbmodem[0-9]*$"`

if [[ -z $_upload_port ]] ; then
  echo "fatal: Cannot find any valid upload port at '/dev/tty.*'."
  exit 1
fi

_upload_port="/dev/tty.$_upload_port"

# Prompt
# ------------------------------------------------
echo "Environment: `stylize $_environment`"
echo "Upload Port: `stylize $_upload_port`"
print-row -

# Run
# ------------------------------------------------
if platformio run --target upload --environment $_environment --upload-port=$_upload_port; then
  _message="Success."
else
  _message="Failed to upload."
fi

# Notify
# ------------------------------------------------
notify "Upload" $_message

if prompt "Open Serial TTY?"; then
  screen $_upload_port 9600
fi

